default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: akine
  password: root
  host: localhost

development:
  <<: *default
  database: heroku_sample_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: heroku_sample_test

production:
  <<: *default
  database: heroku_sample_production
  username: akine
  password: root
